[package]
name = "duck_web_core"
version = "0.1.0"
edition = "2024"

[dependencies]
lazy_static = "1.4"
regex = "1.5"
ctor = "0.2"
parking_lot = "0.12"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"

