[package]
name = "duck_web_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
duck_web_core = { path = "../duck_web_core" }
ctor = "0.2.9"
stringcase = "0.3.0"
